version: "3.8"

services:
  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebsvr
    ports:
      - "8080:80"

  git-server:
      build:
        dockerfile: gitserver.Dockerfile
        context: .
      restart: always
      ports:
        - "3000:3000"
      volumes:
        - ./repos:/var/www/git

